### ISSUE TITLE
Since last night, export operations never ending

### ISSUE THREAD

**Issue by Khayoann2** [microsoft/fhir-server#3425]
**Describe the bug**
When we create a new export operation using Azure API for fhir, the operation is created but stuck in 202 accepted. The operation never ending and could be related to the last release.

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Get Fhir token 
2. Invoke-RestMethod 'https://$FhirHostname/$export?_container=testcontainer&_since=2023-07-25T10%3A00%3A00' -Method 'GET' -headers $headers  
3. Invoke-RestMethod 'https://$FhirHostname/_operations/export/$operationId' -Method 'GET' -headers $headers
4. After multiple hours, the operation is still respond with a 202 accepted

**Expected behavior**
Have a 200 success after operation succeeded or have a 4xx or 5xx with an explicit error to indicate the issue

**Actual behavior**
The export operation never ending and don't send back any information regarding the real status of the operation

AB#105645

**Comment by Khayoann2** [comment]
Hi again,
Any news from your side ?
Thank you ;)

**Comment by brendankowitz** [comment]
Sorry for the delay, our job agent failed to start after the last release. This has been rolled back and will be fixed in a coming update. For jobs that are stuck, I'd recommend cancelling and requeuing to get them going

**Comment by EXPEkesheth** [comment]
@Khayoann2 can you please confirm the issue is resolved ?

**Comment by Khayoann2** [comment]
Yes, the issue is resolved

**Comment by Khayoann2** [comment]
Since tuesday, we got some weird issues.
Export is not working on our side and we have some weird metrics about the collection size and index increased a lot.

**Comment by Khayoann2** [comment]
I see that you rollbacked again so i can close the issue now.
Hope that i will not open it again for the next release 😶‍🌫️ 
We still have an increase of db size (logs apparently) but our fhir accounts are working as expected 👍 
Thank you to the team 👍

**Comment by EXPEkesheth** [comment]
@Khayoann2 - Thanks for your patience, as we worked on the issue ! Can you please share your FHIR instance name by sending email to kesheth@microsoft.com?
